sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - AR=3.2.22.5
    - AR=4.0.13
    - AR=4.1.16
    - AR=4.2.8
    - AR=5.0.3
    - AR=5.1.1
matrix:
  exclude:
    - rvm: 1.9.3
      env: AR=5.0.3
    - rvm: 1.9.3
      env: AR=5.1.1
    - rvm: 2.0.0
      env: AR=5.0.3
    - rvm: 2.0.0
      env: AR=5.1.1
    - rvm: 2.1.10
      env: AR=5.0.3
    - rvm: 2.1.10
      env: AR=5.1.1
    - rvm: 2.4.1
      env: AR=3.2.22.5
    - rvm: 2.4.1
      env: AR=4.0.13
    - rvm: 2.4.1
      env: AR=4.1.16
before_script:
  - mysql -e 'create database seeder_test;'
