cache: bundler
language: ruby
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.8
  - 2.6.6
  - 2.7.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - AR=5.0.3
    - AR=5.1.1
    - AR=5.2.2
    - AR=6.0.3.3
matrix:
  exclude:
    - rvm: 2.1.10
      env: AR=5.0.3
    - rvm: 2.1.10
      env: AR=5.1.1
    - rvm: 2.1.10
      env: AR=6.0.3.3

    - rvm: 2.2.7
      env: AR=6.0.3.3

    - rvm: 2.3.4
      env: AR=6.0.3.3

    - rvm: 2.4.1
      env: AR=6.0.3.3

    - rvm: 2.5.8
      env: AR=6.0.3.3

    - rvm: 2.6.6
      env: AR=6.0.3.3
before_script:
  - mysql -e 'create database seeder_test;'
