sudo: false
cache: bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - AR=3.2.18
    - AR=4.0.5
    - AR=4.1.1
    - AR=4.2.5
before_script:
  - mysql -e 'create database seeder_test;'
