sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - AR=5.0.3
    - AR=5.1.1
    - AR=5.2.2
matrix:
  exclude:
    - rvm: 2.0.0
      env: AR=5.0.3
    - rvm: 2.0.0
      env: AR=5.1.1
    - rvm: 2.1.10
      env: AR=5.0.3
    - rvm: 2.1.10
      env: AR=5.1.1
before_script:
  - mysql -e 'create database seeder_test;'
